version: '3'
services:
  jupyter:
    platform: 'linux/amd64'
    build:
      context: ./jupyter
    volumes:
      - ./ipynb/:/home/jovyan/work
      - ./data/:/home/jovyan/work/data
    ports:
      - 8888:8888
    environment:
      - JUPYTER_PASS=password
